#!/usr/bin/env bash
# Script to install and configure Nginx web server

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo."
    exit 1
fi

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Configure Nginx to return "Hello World!" at the root
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
