#!/usr/bin/env bash
# Install nginx with the -y flag for non-interactive installation
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a configuration file for the redirection
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations...

}" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and restart
sudo nginx -t && sudo service nginx restart

# Output success message
echo "Nginx installed, configured, and redirection set up."
