#!/usr/bin/env bash
# Install Nginx if not already installed

sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

}" | sudo tee /etc/nginx/sites-available/not_found_page

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/not_found_page /etc/nginx/sites-enabled/

# Test Nginx configuration and restart
sudo nginx -t && sudo service nginx restart
