#!/usr/bin/env bash

# Install Nginx with the -y flag for non-interactive installation
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file for the custom 404 page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page.</h1>
</body>
</html>" | sudo tee /var/www/html/404.html > /dev/null

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    # Additional server configurations...

}" | sudo tee /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration and restart
sudo nginx -t && sudo service nginx restart

# Output success message
echo "Nginx installed, configured with custom 404 page."
