#!/usr/bin/env bash
# Displays the listening ports, their PID, and the program's name.
# Show active internet connections (only servers)
echo "Active Internet connections (only servers)"
ss -tulnep | grep 'LISTEN'
echo ""

# Show active UNIX domain sockets (only servers)
echo "Active UNIX domain sockets (only servers)"
ss -xln
