#!/usr/bin/env bash
# Bash script to configure Nginx to listen on port 80

# Update Nginx configuration
sed -i 's/listen 80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
