#!/usr/bin/env bash
# Displays a list of currently running processes showing all processes, for all users,
#including those which might not have a TTY. in a user-oriented format
#and showing the process hierarchy.

ps auxf
