#!/usr/bin/env bash
# This script sends a SIGTERM to the 7-highlander process.

PID=$(pgrep -f "7-highlander")

if [[ -n "$PID" ]]; then
    /bin/kill -s SIGTERM "$PID"
else
    echo "7-highlander Terminated"
fi
