#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely.Also reacts to SIGTERM with "I am invincible!!!"

terminate_handler() {
    echo "I am invincible!!!"
}

trap terminate_handler SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
