#!/usr/bin/env bash
# Displays info about users from previous /etc/passwd file.

while IFS=: read -r username password userID groupID userIDInfo homeDirectory commandShell; do
    echo "The user $username is part of the $groupID gang, lives in $homeDirectory and rides $commandShell. $userID's place is protected by the passcode $password, more info about the user here: $userIDInfo"
done < /etc/passwd
