#!/usr/bin/env bash

# Copy the /etc/hosts to a new file
cp /etc/hosts ~/hosts.new

# Change localhost to 127.0.0.2
sed -i 's/^127.0.0.1\s*localhost/127.0.0.2 localhost/' ~/hosts.new

# Modify facebook.com entry to 8.8.8.8.
if grep -q "facebook.com" ~/hosts.new; then
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new
else
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

cp -f ~/hosts.new /etc/hosts

rm ~/hosts.new
