#!/usr/bin/env bash
# This script extracts and displays all active IPv4 addresses from the output of 'ifconfig'.
# It first filters lines containing IPv4 addresses using 'grep', and then trims the extraneous
# details to show only the IP addresses using 'cut'.
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
