#!/usr/bin/env bash

echo "Before Reload:"
ps auxf | grep '[g]unicorn'

# Gracefully reload Gunicorn by sending a HUP signal to the master
pkill -HUP -f '[g]unicorn'

# Check if the reload was successful
if pkill -0 -f '[g]unicorn'; then
    echo "OK"
else
    echo "Reload Failed" >&2
fi
