#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school

# Connect to the server using ssh with the specified private key and user
ssh -i ~/.ssh/school ubuntu@54.160.95.117
